from typing import Any

Mailable = Any

class Mail:
    """Mail facade."""

    @staticmethod
    def add_driver(name: str, driver: Any): ...
    @staticmethod
    def set_configuration(config: dict) -> "Mail": ...
    @staticmethod
    def get_driver(name: str | None = None) -> Any: ...
    @staticmethod
    def get_config_options(driver: str | None = None) -> dict: ...
    @staticmethod
    def mailable(mailable: "Mailable") -> "Mail": ...
    @staticmethod
    def send(driver: str | None = None): ...
