from typing import Any

class Queue:
    @staticmethod
    def add_driver(name: str, driver: str): ...
    @staticmethod
    def get_driver(name: str) -> Any: ...
    @staticmethod
    def set_configuration(config: dict) -> "Queue": ...
    @staticmethod
    def get_config_options(driver: str) -> dict: ...
    @staticmethod
    def push(*jobs, **options) -> None: ...
    @staticmethod
    def consume(options: dict) -> Any: ...
    @staticmethod
    def retry(options: dict) -> Any: ...
