from collections.abc import Awaitable, Callable, Iterable, Mapping
from typing import Any, overload

from redis.asyncio.client import Pipeline

from fastapi_startkit.redis import Connection, RedisManager

class Redis:
    @staticmethod
    def connection(name: str | None = None) -> Connection: ...
    @staticmethod
    def connections() -> dict[str, Connection]: ...
    @staticmethod
    def extend(client: str, factory: Callable[[dict[str, Any]], Any]) -> RedisManager: ...
    @staticmethod
    async def purge(name: str | None = None) -> None: ...
    @staticmethod
    async def disconnect() -> None: ...
    @staticmethod
    async def command(method: str, parameters: Iterable[Any] | None = None) -> Any: ...
    @overload
    @staticmethod
    def pipeline(callback: None = None) -> Pipeline: ...
    @overload
    @staticmethod
    def pipeline(callback: Callable[[Pipeline], Any]) -> Awaitable[list[Any]]: ...
    @overload
    @staticmethod
    def transaction(callback: None = None) -> Pipeline: ...
    @overload
    @staticmethod
    def transaction(callback: Callable[[Pipeline], Any]) -> Awaitable[list[Any]]: ...
    @staticmethod
    async def subscribe(channels: str | Iterable[str], callback: Callable[[Any, Any], Any]) -> None: ...
    @staticmethod
    async def psubscribe(patterns: str | Iterable[str], callback: Callable[[Any, Any], Any]) -> None: ...
    @staticmethod
    async def publish(channel: str, message: Any) -> int: ...
    @staticmethod
    async def eval(script: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    @staticmethod
    async def evalsha(sha: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    @staticmethod
    async def get(name: str) -> Any: ...
    @staticmethod
    async def set(
        name: str,
        value: Any,
        ex: int | None = None,
        px: int | None = None,
        nx: bool = False,
        xx: bool = False,
        keepttl: bool = False,
        get: bool = False,
    ) -> Any: ...
    @staticmethod
    async def setex(name: str, time: int, value: Any) -> Any: ...
    @staticmethod
    async def setnx(name: str, value: Any) -> bool: ...
    @staticmethod
    async def mget(keys: str | Iterable[str], *args: str) -> list[Any]: ...
    @staticmethod
    async def mset(mapping: Mapping[str, Any]) -> bool: ...
    @staticmethod
    async def delete(*names: str) -> int: ...
    @staticmethod
    async def exists(*names: str) -> int: ...
    @staticmethod
    async def expire(name: str, time: int) -> bool: ...
    @staticmethod
    async def ttl(name: str) -> int: ...
    @staticmethod
    async def incr(name: str, amount: int = 1) -> int: ...
    @staticmethod
    async def incrby(name: str, amount: int = 1) -> int: ...
    @staticmethod
    async def decr(name: str, amount: int = 1) -> int: ...
    @staticmethod
    async def decrby(name: str, amount: int = 1) -> int: ...
    @staticmethod
    async def keys(pattern: str = "*") -> list[Any]: ...
    @staticmethod
    async def hget(name: str, key: str) -> Any: ...
    @staticmethod
    async def hset(
        name: str, key: str | None = None, value: Any = None, mapping: Mapping[str, Any] | None = None
    ) -> int: ...
    @staticmethod
    async def hgetall(name: str) -> dict[Any, Any]: ...
    @staticmethod
    async def hdel(name: str, *keys: str) -> int: ...
    @staticmethod
    async def lpush(name: str, *values: Any) -> int: ...
    @staticmethod
    async def rpush(name: str, *values: Any) -> int: ...
    @staticmethod
    async def lpop(name: str, count: int | None = None) -> Any: ...
    @staticmethod
    async def rpop(name: str, count: int | None = None) -> Any: ...
    @staticmethod
    async def lrange(name: str, start: int, end: int) -> list[Any]: ...
    @staticmethod
    async def sadd(name: str, *values: Any) -> int: ...
    @staticmethod
    async def srem(name: str, *values: Any) -> int: ...
    @staticmethod
    async def smembers(name: str) -> set[Any]: ...
    @staticmethod
    async def zadd(name: str, mapping: Mapping[str, float], nx: bool = False, xx: bool = False) -> int: ...
    @staticmethod
    async def zrange(name: str, start: int, end: int, withscores: bool = False) -> list[Any]: ...
    @staticmethod
    async def flushdb(asynchronous: bool = False) -> bool: ...
    @staticmethod
    async def ping() -> bool: ...
